fail_fast: true
default_stages: [commit]

repos:
  - repo: local
    hooks:
      - id: run-linters.sh
        name: run-linters.sh
        language: script
        entry: "./dev/linters.sh"
        always_run: true