version: "3.7"

services:
  api:
    container_name: api
    image: fastapi_base:dev
    build:
      context: .
      args:
        - ENV=dev
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: start.sh
